# Exported from Render on 2025-01-20T01:44:02Z
services:
- type: web
  name: uniaccess
  runtime: ruby
  repo: https://github.com/HectorMed/residencia_QR_APP
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
version: "1"
